[package]
name = "os"
version = "0.1.0"
authors = ["RainaX <xiaofanx@andrew.cmu.edu>"]
edition = "2018"


[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
